version: '3.8'

services:
  face-analyzer:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./static/uploads:/app/static/uploads  # Чтобы сохранялись загруженные картинки
    restart: unless-stopped